#!/bin/bash

# waitfor <time> <pid>

time=$1
pid=$2

n=0
while true; do
        stat "/proc/$pid" >/dev/null 2>&1 || break
        sleep 1
        if (( ++n > $time )); then
                exit 1
        fi
        
done

exit 0
